import Head from 'next/head'
import { Inter } from 'next/font/google'
import Instruction from '../components/Instructions/index'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Game whit Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <div className={styles.containerItems}>
            <Link href="./juegoinicio/juego">
              <h1>Jugar</h1>
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}
